# Dependencies
FROM node:18.20-alpine3.19 as deps

WORKDIR /usr/src/app

COPY package*.json ./
COPY yarn.lock ./

RUN yarn install


# Builder
FROM node:18.20-alpine3.19 as builder

WORKDIR /usr/src/app

COPY --from=deps /usr/src/app/node_modules ./node_modules

COPY . .

RUN yarn build

RUN yarn install --production --frozen-lockfile && yarn cache clean --force

RUN yarn prisma generate


# Create final docker image
FROM node:18.20-alpine3.19 as prod

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/node_modules ./node_modules

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/prisma ./prisma

ENV NODE_ENV=production

USER node

EXPOSE 3000

CMD [ "node", "dist/main.js" ]